version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: widen
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      fortawesome-dependencies:
        patterns:
          - "@fortawesome/*"
      gatsby-dependencies:
        patterns:
          - "gatsby"
          - "gatsby-*"
      react-dependencies:
        patterns:
          - "react"
          - "react-*"
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
