name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: escemi-tech/actions-node@v1.7.0
        with:
          build: "build:ci"
          checks: true

  gh-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: github-pages
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - uses: escemi-tech/actions-node@v1.7.0
        with:
          build: "build:deploy"

      - name: 🚀 Release to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔭 Check the site is up
        uses: srt32/uptime@v0.2.1
        with:
          url-to-hit: ${{ secrets.DEPLOY_URL }}
          expected-statuses: "200"
